# Generated by Django 4.1.5 on 2023-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Libro', models.CharField(max_length=150)),
                ('Autor', models.CharField(max_length=150)),
                ('Editorial', models.CharField(max_length=150)),
            ],
        ),
    ]
